//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoriaViva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EspacoMemoriaVivaEntities1 : DbContext
    {
        public EspacoMemoriaVivaEntities1()
            : base("name=EspacoMemoriaVivaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<FILE> FILE { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PHONE> PHONE { get; set; }
        public virtual DbSet<PROFESSIONAL> PROFESSIONAL { get; set; }
        public virtual DbSet<PROFESSIONAL_TYPE> PROFESSIONAL_TYPE { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<SERVICE_PROVIDER> SERVICE_PROVIDER { get; set; }
        public virtual DbSet<UNPAID_BILLS> UNPAID_BILLS { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
    }
}
