//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoriaViva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESSIONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESSIONAL()
        {
            this.SERVICE = new HashSet<SERVICE>();
        }
    
        public int Id { get; set; }
        public int Person_Id { get; set; }
        public int ProfessionalType_Id { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual PROFESSIONAL_TYPE PROFESSIONAL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE> SERVICE { get; set; }
    }
}
