//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoriaViva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE()
        {
            this.UNPAID_BILLS = new HashSet<UNPAID_BILLS>();
            this.FILE = new HashSet<FILE>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Professional_Id { get; set; }
        public int ServiceProvider_Id { get; set; }
        public int Client_Id { get; set; }
        public string Description { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROFESSIONAL PROFESSIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNPAID_BILLS> UNPAID_BILLS { get; set; }
        public virtual SERVICE_PROVIDER SERVICE_PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE> FILE { get; set; }
    }
}
