//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoriaViva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNPAID_BILLS
    {
        public int Id { get; set; }
        public decimal Value { get; set; }
        public int PaymentMethod_Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Service_Id { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
    }
}
